name: Build and Deploy

on:
  push:
    branches: 
    - "main"
    - "hml"
    - "dev"
    - "feature/*"

jobs:
  call-shared-workflow:
    uses: ./.github/workflows/k8s-deploy-v6.yaml
    secrets: inherit
    with:
      namespace: matrix-apps  # Application Namespace ( Project )
      values: .ci/values.yaml # Where the app config is relative to root
      tokenName: NPM_TOKEN    # Token to install dependencies - for using at pip or .npmrc