name: Build and Deploy

on:
  push:
    branches: 
    - "main"
    - "hml"
    - "dev"
    - "feature/*"

jobs:
  call-shared-workflow:
    uses: ./.github/workflows/k8s-deploy-v5.yaml
    secrets: inherit
    with:
      namespace: matrix-apps
      port: 3000
      replicas: 1
      external: true
      auth: false
      removePathPrefix: true