name: Default pipeline to ACR

on:
  push:
    branches: 
    - "main"
    - "hml"
    - "dev/*"
  pull_request:
    branches: 
    - "main"

jobs:
  configure-build-push-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Is Prod
        if: github.ref_name == 'main'
        run: |
          echo "ENVIRONMENT_LOWER=prd" >> $GITHUB_ENV
          echo "ENVIRONMENT=PRD" >> $GITHUB_ENV      
    
      - name: Is Homolog
        if: github.ref_name == 'hml'
        run: |
          echo "ENVIRONMENT_LOWER=hml" >> $GITHUB_ENV
          echo "ENVIRONMENT=HML" >> $GITHUB_ENV
      - name: Is Dev
        if: ( github.ref_name != 'main' && github.ref_name != 'hml' )
        run: |
          echo "ENVIRONMENT_LOWER=dev" >> $GITHUB_ENV
          echo "ENVIRONMENT=DEV" >> $GITHUB_ENV
      - name: Set Secrets Vars
        run: |
          echo REGISTRY_NAME=${{ env.ENVIRONMENT_LOWER }}akscr.azurecr.io >> $GITHUB_ENV
          echo RESOURCE_GROUP=matrix-${{ env.ENVIRONMENT_LOWER }} >> $GITHUB_ENV
          echo CLUSTER_NAME=matrix-${{ env.ENVIRONMENT_LOWER }} >> $GITHUB_ENV          
          echo REGISTRY_USR=MATRIX_${{ env.ENVIRONMENT }}_ACR_USERNAME >> $GITHUB_ENV
          echo REGISTRY_PWD=MATRIX_${{ env.ENVIRONMENT }}_ACR_PASSWORD >> $GITHUB_ENV
          echo KUBE_CONFIG=MATRIX_${{ env.ENVIRONMENT }}_AKS_KUBE_CONFIG >> $GITHUB_ENV
      
      - name: Docker Login
        uses: Azure/docker-login@v1
        with:
          login-server: ${{ env.REGISTRY_NAME }}
          username: ${{ secrets[env.REGISTRY_USR] }}
          password: ${{ secrets[env.REGISTRY_PWD] }}

      - name: Docker Build and Push
        ## running string operator to make repository name lower-case
        run: |
          docker build . -t ${REGISTRY_NAME}/${GITHUB_REPOSITORY,,}:${GITHUB_SHA} -t ${REGISTRY_NAME}/${GITHUB_REPOSITORY,,}:${ENVIRONMENT_LOWER}-latest
          docker push ${REGISTRY_NAME}/${GITHUB_REPOSITORY,,}:${GITHUB_SHA}
          docker push ${REGISTRY_NAME}/${GITHUB_REPOSITORY,,}:${ENVIRONMENT_LOWER}-latest