name: Build and Deploy


on:
  push:
    branches:
    - "main"
    - "hml"
    - "dev"
    
jobs:
  call-shared-workflow:
    uses: Matrix-Energia/matrix.devops.pipelines/.github/workflows/k8s-swa.yml@<--set the pipeline version here-->
    secrets: inherit
    with:
      node-version: 16.14.2
      build-command: npm ci && npm run build && npm run generate
      namespace: matrix-webpages
      external: true
      output-dir: dist