name: k8s Api

env:
  HELM_VERSION: v3.9.2
  CHART_REPOSITORY: 'Matrix-Energia/matrix.devops.template.charts.git'
  CHART_REVISION: v7
  CHART_PATH: charts
  CHART_TYPE: api
  GIT_TOKEN_NAME: GIT_TOKEN_CUSTOM

on:
  workflow_call:
    inputs:
      namespace:
        type: string
        required: false
        default: matrix-apps
      values:
        type: string
        required: false
        default: .ci/values.yaml
      tokenName:
        type: string
        required: false
        default: GIT_TOKEN

jobs:
  configuration:
    runs-on: ubuntu-latest
    outputs:
      app-name: ${{ steps.configure.outputs.app-name }}
      app-revision: ${{ steps.configure.outputs.app-name }}
      app-tag: ${{ steps.configure.outputs.app-tag }}
      app-image: ${{ steps.configure.outputs.app-image }}
      app-config-name: ${{ steps.configure.outputs.app-config }}
      kube-config: ${{ steps.configure.outputs.app-config.kube-config }}   
      registry_addr: ${{ steps.configure.outputs.registry_addr }}
      registry_name: ${{ steps.configure.outputs.registry_name }}
      registry_usr: ${{ steps.configure.outputs.registry_usr }}
      registry_pwd: ${{ steps.configure.outputs.registry_pwd }}
      app-config-b64: ${{ steps.parse-variables.outputs.app-config-b64 }} # This parses the env var form a complex yaml to scalar properties then convert b64 encode it

    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive
          token: ${{ secrets[env.GIT_TOKEN_NAME] }}

      - name: prd
        if: github.ref_name == 'main'
        run: |
          echo "ENVIRONMENT=PRD"                >> $GITHUB_ENV
          echo "ENVIRONMENT_LOWER=prd"          >> $GITHUB_ENV
          echo "APP_REVISION=prd"               >> $GITHUB_ENV

      - name: hml
        if: github.ref_name == 'hml'
        run: |
          echo "ENVIRONMENT=HML"                >> $GITHUB_ENV
          echo "ENVIRONMENT_LOWER=hml"          >> $GITHUB_ENV
          echo "APP_REVISION=hml"               >> $GITHUB_ENV

      - name: not prd or hml
        if: ( github.ref_name != 'main' && github.ref_name != 'hml' )
        run: |
          REV_NAME=${GITHUB_REF_NAME,,}
          echo "ENVIRONMENT=DEV"                >> $GITHUB_ENV
          echo "ENVIRONMENT_LOWER=dev"          >> $GITHUB_ENV
          echo "APP_REVISION=${REV_NAME//\//-}" >> $GITHUB_ENV

      - name: configure
        run: |
          APP_NAME="${GITHUB_REPOSITORY/'Matrix-Energia/'/}"
          APP_NAME="${APP_NAME/matrix./}"
          APP_NAME="${APP_NAME//./-}"
          APP_TAG="${GITHUB_SHA:0:8}-${GITHUB_RUN_NUMBER}"
          APP_IMAGE="${REGISTRY_NAME}/${GITHUB_REPOSITORY,,}"
          APP_CONFIG="${ENVIRONMENT}_CONFIG"
          KUBE_CONFIG="MATRIX_${ENVIRONMENT}_AKS_KUBE_CONFIG"
          REGISTRY_NAME="${ENVIRONMENT_LOWER}akscr.azurecr.io"
          REGISTRY_USR="MATRIX_${ENVIRONMENT}_ACR_USERNAME"
          REGISTRY_PWD="MATRIX_${ENVIRONMENT}_ACR_PASSWORD"
          echo "::set-output name=environment::${ENVIRONMENT_LOWER}"
          echo "::set-output name=app-name::${APP_NAME}"
          echo "::set-output name=app-revision::${APP_REVISION}"
          echo "::set-output name=app-tag::${APP_TAG}"
          echo "::set-output name=app-image::${APP_IMAGE}"
          echo "::set-output name=app-config-name::${APP_CONFIG}"
          echo "::set-output name=kube-config::${KUBE_CONFIG}"
          echo "::set-output name=registry_name::${REGISTRY_NAME}"
          echo "::set-output name=registry_usr::${REGISTRY_USR}"
          echo "::set-output name=registry_pwd::${REGISTRY_PWD}"

      - name: make yaml cfg plain
        id: parse-variables
        uses: mikefarah/yq@master
        with: 
          cmd: |
            echo ${{ secrets[steps.configuration.outputs.app-config-name] }} > .cfg
            cat app_cfg | base64 -d | yq e '.. | select(. == "*") | {(path | . as $x | (.[] | select((. | tag) == "!!int") |= (["[", ., "]"] | join(""))) | $x | join(".") | sub(".\[", "[")): .} ' - | base64 -w0 > .cfg
            echo "::set-output name=app-config-b64::$(cat .cfg)"

  configure-docker:
    runs-on: ubuntu-latest
    needs: [ configuration ]
    steps:
      - name: docker login
        uses: Azure/docker-login@v1
        with:
          login-server: ${{ needs.configuration.outputs.registry_name }}
          username: ${{ secrets[needs.configuration.outputs.registry_usr] }}
          password: ${{ secrets[needs.configuration.outputs.registry_pwd] }}
          
  build-and-push:
    runs-on: ubuntu-latest
    needs: [ configuration, configure-docker ]
    steps:
      - name: docker build
        run: |
          docker build \
            --build-arg ${{ inputs.tokenName }}=${{ secrets.PACKAGES_TOKEN }} \
            -t ${{ needs.configuration.outputs.app-image }}:${{ needs.configuration.outputs.app-tag }} \
            -t ${{ needs.configuration.outputs.app-image }}:latest \
            .
      - name: docker push
        run: docker push --all-tags ${{ needs.configuration.outputs.app-image }}

  setup-k8s:
    runs-on: ubuntu-latest
    needs: [ configuration ]
    steps:
      - name: connect to cluster
        uses: Azure/k8s-set-context@v2
        with:
          kubeconfig: ${{ secrets[steps.configuration.outputs.kube-config] }}

  setup-helm-tool:
    runs-on: ubuntu-latest
    needs: [ configuration, setup-k8s ]
    steps:
      - name: install helm tool
        uses: azure/setup-helm@v3
        with:
          version: ${{ env.HELM_VERSION }}

  setup-helm-chart:
    runs-on: ubuntu-latest
    steps:
      - name: clone helms
        uses: actions/checkout@v3
        with:
          repository: ${{ env.CHART_REPOSITORY }}
          ref: ${{ env.CHART_REVISION }}
          path: ${{ env.CHART_PATH }}
          token: ${{ secrets[env.GIT_TOKEN_NAME] }}

  helm:
    runs-on: ubuntu-latest
    needs: [ configuration, build-and-push, setup-k8s, setup-helm-tool, setup-helm-chart ]
    steps:
      - name: install helm chart
        run: |
          helm upgrade ${{ needs.configuration.outputs.app-name }}-${{ needs.configuration.outputs.app-revision }} \
            ${{ env.CHART_PATH }}/${{ env.CHART_TYPE }} \
            --install \
            --wait \
            --timeout 6m0s \
            --namespace '${{ inputs.namespace }}' \
            --values    '${{ inputs.values }}' \
            --set       environment='${{ needs.configuration.outputs.environment }}' \
            --set       image='${{ needs.configuration.outputs.app-image }}:${{ needs.configuration.outputs.app-tag }}' \
            --set       repository='${{ github.repository }}' \
            --set       config='${{ needs.configuration.outputs.app-config-b64 }}'
