name: Java with Nexus Repository 

on: 
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: snapshots
        if: ( github.ref_name != 'releases')
        run: |
          echo "ENVIRONMENT=SNAPSHOT" >> $GITHUB_ENV
          echo "APP_REVISION=${GITHUB_REF_NAME//\//-}" >> $GITHUB_ENV
      - name: main
        if: github.ref_name == 'main'
        run: |
          echo "ENVIRONMENT=RELEASES" >> $GITHUB_ENV
          echo "APP_REVISION=RELEASES" >> $GITHUB_ENV
      - name: set-vars
        run: |
          APP_NAME="${GITHUB_REPOSITORY/'Matrix-Energia/'/}"
          APP_NAME="${APP_NAME/matrix./}"
          ENVIRONMENT_LOWER="${ENVIRONMENT,,}"
          SERVER_HOST="${{ secrets.NEXUS_HOST }}"
          echo ${{ secrets.NEXUS_HOST }}
      - uses: actions/checkout@v1
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      #- name: Build with Maven
       # run: mvn package --file pom.xml && pwd && ls -la
      - name: Deploy to Nexus
        run: |
          mvn deploy:deploy-file \
            -Durl=${{env.SERVER_HOST}} \
            -DrepositoryId=${{ env.APP_NAME }}-${{ env.ENVIRONMENT_LOWER }} \
            -DgroupId=com.matrix \
            -DartifactId=${{ env.APP_NAME }} \
            -Dversion=1.0.0 \
            -Dpackaging=pom \
            -Dfile=/home/runner/work/matrix.java.ms.lib/matrix.java.ms.lib/pom.xml \
            -DgeneratePom=true \
            -DpomFile=pom.xml \
            -Dusername=admin \
            -Dpassword=${{ secrets.NEXUS_PASSWORD }}
