name: Java with Nexus Repository
on: 
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: snapshots
      if: ( github.ref_name != 'releases')
      run: |
          echo "ENVIRONMENT=SNAPSHOT" >> $GITHUB_ENV
          echo "APP_REVISION=${GITHUB_REF_NAME//\//-}" >> $GITHUB_ENV
    - name: main
      if: github.ref_name == 'main'
      run: |
          echo "ENVIRONMENT=RELEASES" >> $GITHUB_ENV
          echo "APP_REVISION=RELEASES" >> $GITHUB_ENV
    - name: set-vars
      run: |
          APP_NAME="${GITHUB_REPOSITORY/'Matrix-Energia/'/}"
          APP_NAME="${APP_NAME/matrix./}"
          ENVIRONMENT_LOWER="${ENVIRONMENT,,}"
    - name: Build with Maven
      run: mvn package --file pom.xml
    - name: Nexus Repo Publish
      uses: sonatype-nexus-community/nexus-repo-github-action@master
      with:
        serverUrl: ${{ secrets.NEXUS_HOST }}
        username: admin
        password: ${{ secrets.NEXUS_PASSWORD }}
        format: maven2
        repository: java-ms-lib
        coordinates: groupId=com.matrix artifactId=java-ms-lib version=1.0.0
        assets: extension=xml
        filename: pom.xml
