name: Java with Nexus Repository 

on: 
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: snapshots
        if: ( github.ref_name != 'releases')
        run: |
          echo "ENVIRONMENT=SNAPSHOTS" >> $GITHUB_ENV
          echo "APP_REVISION=${GITHUB_REF_NAME//\//-}" >> $GITHUB_ENV
      - name: releases
        if: github.ref_name == 'releases'
        run: |
          echo "ENVIRONMENT=RELEASES" >> $GITHUB_ENV
          echo "APP_REVISION=RELEASES" >> $GITHUB_ENV
      - name: set-vars
        run: |
          APP_NAME="${GITHUB_REPOSITORY/'Matrix-Energia/'/}"
          APP_NAME="${APP_NAME/matrix./}"
          ENVIRONMENT_LOWER="${ENVIRONMENT,,}"
          SERVER_HOST=${{ secrets.NEXUS_HOST }}
          echo SERVER_HOST
      - uses: actions/checkout@v1
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Build with Maven
        run: mvn package --file pom.xml && pwd && ls -la
      - name: Nexus Repo Publish
        uses: sonatype-nexus-community/nexus-repo-github-action@master
        with:
          serverUrl: ${{ env.SERVER_HOST }}
          username: admin
          password: ${{ secrets.NEXUS_PASSWORD }}
          format: maven2
          repository: ${{ env.APP_NAME }}-${{ env.ENVIRONMENT_LOWER }}
          coordinates: groupId=com.matrix artifactId=${{ env.APP_NAME }} version=1.0.0
          assets: extension=xml
          filename: pom.xml
